server:
  port: 8081
spring:
  application:
    name: xingchencomments
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://110.40.211.224:3306/xingchenComments?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 419520
  redis:
    host: 110.40.211.224
    port: 6379
    password: 419520
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl